Detect ChromeOS and treat it like Android
braintree/restricted-input pull request #61
Opened 2019-08-08 03:56 UTC by gesa

On the long march to conquer the Chromebook soft keyboard bug, this PR updates the braintree/browser-detection package and makes sure ChromeOS inputs are handled like Android inputs.

2019-08-08 17:14 UTC, hollabaq86 approved these changes
👍

2019-08-08 19:53 UTC, crookedneighbor commented on version
> +#!/bin/bash
Can we do this as part of a separate PR?

Probably needs a post publish script that also adds an `unreleased` section if we want to automate this fully.

2019-08-08 19:57 UTC, crookedneighbor requested changes
Can we take out the version script stuff? If we want to automate it, we should fully do it and do it as a separate PR, IMO.

Does setting a version script override the normal `npm version` task? Or does it occur before? or what? Any reason it can't be `preversion` instead?

(all questions for a separate PR, IMO)

2019-08-12 20:20 UTC, gesa commented
@crookedneighbor fair enough. i had actually only added it in this PR bc i noticed in the log that historically the tag commit is the _same_ commit as the changelog. also this lib is tiny. i'll open a new PR with answers to your Qs.

2019-08-13 16:10 UTC, crookedneighbor approved these changes

2019-08-13 16:10 UTC, merged